name: Formatting and Validation for Packer

on: 
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v3

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2

      - name: Run Packer init
        run: packer init ./packer

      - name: Run Packer Format Check
        run: packer fmt -check -diff ./packer

      - name: Run Packer Validate
        env:
          AMI_Name: ${{ vars.AMI_NAME }}
          Instance_Type: ${{ vars.INSTANCE_TYPE }}
          AWS_Region: ${{ vars.AWS_REGION }}
          Ubuntu_AMI_Image: ${{ vars.UBUNTU_AMI_IMAGE }}
          SSH_User_Name: ${{ vars.UBUNTU_USER_NAME }}
          MySQL_UserName: ${{ secrets.DB_USERNAME }}
          MySQL_Password: ${{ secrets.DB_PASSWORD }}
          DB_Name: ${{ vars.DB_NAME }}
          Port: ${{ vars.PORT }}
          Host: ${{ vars.HOST }}
          Account_IDs: ${{ secrets.ACCOUNT_IDS }}

        run: |
          export PACKER_LOG=1
          packer validate \
            -var "ami_name1=AMI_Name" \
            -var "instance_type1=Instance_Type" \
            -var "aws_region1=us-AWS_Region" \
            -var "ubuntu_ami_image1=Ubuntu_AMI_Image" \
            -var "ssh_username1=SSH_User_Name" \
            -var "mysql_user=MySQL_UserName" \
            -var "mysql_password=MySQL_Password" \
            -var "mysql_host=Host" \
            -var "db_name=DB_Name" \
            -var "app_port=Port" \
            -var "account_ids1=Account_IDs" \
            ./packer/aws-ubuntu.pkr.hcl
