name: Packer Build and instance refresh

on:
  pull_request:
    branches:
      - main

jobs:
  packer-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2

      # setting the AWS credentials for dev service account 
      - name: Set up AWS CLI for service account in Dev env
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.SERVICE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SERVICE_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      
      # Commenting the GCP code as we are not using it in this assignment
      # - name: 'google cloud authentication'
      #   uses: google-github-actions/auth@v2
      #   with:
      #       credentials_json: ${{ secrets.GCP_CREDENTIAL }}
  
      # - name: 'Set up GCP SDK'
      #   uses: google-github-actions/setup-gcloud@v2
        
      # - name: 'Set up and use GCP CLI'
      #   run: 'gcloud info'

      # - name: Create /tmp/webapp Directory
      #   run: mkdir -p /tmp/webapp
  
      # - name: Copy Files to /tmp/webapp
      #   run: cp -r $GITHUB_WORKSPACE/* /tmp/webapp/
  
      # - name: List /tmp/webapp Contents
      #   run: ls -lah /tmp/webapp

      - name: Initialize Packer (Install required plugins)
        run: packer init ./packer

      - name: Run Packer Build for AWS
        env:
          AMI_Name: ${{ vars.AMI_NAME }}
          Instance_Type: ${{ vars.INSTANCE_TYPE }}
          AWS_Region: ${{ vars.AWS_REGION }}
          Ubuntu_AMI_Image: ${{ vars.UBUNTU_AMI_IMAGE }}
          SSH_User_Name: ${{ vars.UBUNTU_USER_NAME }}

        run: |
          export PACKER_LOG=1
          packer build \
            -var "ami_name1=${{ env.AMI_Name}}" \
            -var "instance_type1=${{ env.Instance_Type }}" \
            -var "aws_region1=${{ env.AWS_Region }}" \
            -var "ubuntu_ami_image1=${{ env.Ubuntu_AMI_Image }}" \
            -var "ssh_username1=${{ env.SSH_User_Name }}" \
            ./packer/aws-ubuntu.pkr.hcl
      
      - name: Get latest AMI ID
        id: get_ami_id
        run: |
          AMI_ID=$(aws ec2 describe-images --owners self --query 'Images[*].[ImageId,CreationDate]' --output text | sort -k2 -r | head -n1 | cut -f1)
          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV
          echo "Latest AMI ID: $AMI_ID"
        
      - name: Sharing the AMI with DEMO account
        run: |
          aws ec2 modify-image-attribute \
            --image-id ${{ env.AMI_ID }} \
            --launch-permission "Add=[{UserId=${{ secrets.DEMO_AWS_ACCOUNT_ID }}}]"
          echo "AMI shared with demo account"
      
      # switching to demo account
      - name: Configuring AWS credentials for service account in demo env
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DEMO_SERVICE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEMO_SERVICE_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      # waiting for AMI to be available in demo account
      - name: Wait for AMI to be available in demo account
        run: |
          echo "Waiting for AMI to be available in DEMO account..."
          while true; do
            AMI_STATE=$(aws ec2 describe-images --image-ids ${{ env.AMI_ID }} --query 'Images[0].State' --output text 2>/dev/null || echo "pending")
            if [ "$AMI_STATE" = "available" ]; then
              echo "AMI is now available in DEMO account"
              break
            fi
            echo "AMI not yet available. Waiting 10 seconds..."
            sleep 10
          done
      
      # Update Launch Template with new AMI ID
      - name: Update Launch Template
        run: |
          LAUNCH_TEMPLATE_ID=$(aws ec2 describe-launch-templates --query 'LaunchTemplates[?LaunchTemplateName==`csye6225_asg`].LaunchTemplateId' --output text)
          echo "Launch Template ID: $LAUNCH_TEMPLATE_ID"
          
          INSTANCE_TYPE=$(aws ec2 describe-launch-template-versions --launch-template-id $LAUNCH_TEMPLATE_ID --versions '$Latest' --query 'LaunchTemplateVersions[0].LaunchTemplateData.InstanceType' --output text)

          aws ec2 create-launch-template-version \
            --launch-template-id $LAUNCH_TEMPLATE_ID \
            --version-description "Auto-updated AMI via GitHub Actions" \
            --source-version "$Latest" \
            --launch-template-data "{\"ImageId\":\"${{ env.AMI_ID }}\",\"InstanceType\":\"$INSTANCE_TYPE\"}"
            
          # Set the newest version as default
          LATEST_VERSION=$(aws ec2 describe-launch-template-versions --launch-template-id $LAUNCH_TEMPLATE_ID --query 'LaunchTemplateVersions[0].VersionNumber' --output text)
          aws ec2 modify-launch-template --launch-template-id $LAUNCH_TEMPLATE_ID --default-version $LATEST_VERSION
          
          echo "Launch Template updated with new AMI ID"
          
      # Start instance refresh in Auto Scaling Group
      - name: Start Instance Refresh
        id: start-refresh
        run: |
          REFRESH_ID=$(aws autoscaling start-instance-refresh \
            --auto-scaling-group-name app-autoscaling-group \
            --preferences '{"MinHealthyPercentage": 50, "InstanceWarmup": 300}' \
            --query 'InstanceRefreshId' --output text)
            
          echo "REFRESH_ID=$REFRESH_ID" >> $GITHUB_ENV
          echo "Instance refresh started with ID: $REFRESH_ID"
        
       # Wait for instance refresh to complete
      - name: Wait for Instance Refresh to Complete
        run: |
         echo "Waiting for instance refresh to complete..."
         while true; do
           STATUS=$(aws autoscaling describe-instance-refreshes \
             --auto-scaling-group-name app-autoscaling-group \
             --instance-refresh-ids ${{ env.REFRESH_ID }} \
             --query 'InstanceRefreshes[0].Status' --output text)
             
           PERCENTAGE=$(aws autoscaling describe-instance-refreshes \
             --auto-scaling-group-name app-autoscaling-group \
             --instance-refresh-ids ${{ env.REFRESH_ID }} \
             --query 'InstanceRefreshes[0].PercentageComplete' --output text)
             
           echo "Status: $STATUS, Percentage complete: $PERCENTAGE%"
           
           if [ "$STATUS" = "Successful" ]; then
             echo "Instance refresh completed successfully"
             break
           elif [ "$STATUS" = "Failed" ] || [ "$STATUS" = "Cancelled" ]; then
             echo "Instance refresh failed or was cancelled"
             exit 1
           fi
           
           echo "Sleeping for 30 seconds..."
           sleep 30
         done