name: Packer Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2

      # - name: Install AWS CLI
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y awscli
            
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.SERVICE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SERVICE_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Initialize Packer (Install required plugins)
        run: packer init ./packer

      - name: Run Packer Build for AWS
        env:
          AMI_Name: ${{ vars.AMI_NAME }}
          Instance_Type: ${{ vars.INSTANCE_TYPE }}
          AWS_Region: ${{ vars.AWS_REGION }}
          Ubuntu_AMI_Image: ${{ vars.UBUNTU_AMI_IMAGE }}
          SSH_User_Name: ${{ vars.UBUNTU_USER_NAME }}
          MySQL_UserName: ${{ secrets.DB_USERNAME }}
          MySQL_Password: ${{ secrets.DB_PASSWORD }}
          DB_Name: ${{ vars.DB_NAME }}
          Port: ${{ vars.PORT }}
          Host: ${{ vars.HOST }}
          Account_IDs: ${{ secrets.ACCOUNT_IDS }}

        run: |
          export PACKER_LOG=1
          packer build \
            -var "ami_name1=AMI_Name" \
            -var "instance_type1=Instance_Type" \
            -var "aws_region1=us-AWS_Region" \
            -var "ubuntu_ami_image1=Ubuntu_AMI_Image" \
            -var "ssh_username1=SSH_User_Name" \
            -var "mysql_user=MySQL_UserName" \
            -var "mysql_password=MySQL_Password" \
            -var "mysql_host=Host" \
            -var "db_name=DB_Name" \
            -var "app_port=Port" \
            -var "account_ids1=[\"${Account_IDs}\"]"
            ./packer/aws-ubuntu.pkr.hcl
