name: webapp test for CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  app-build:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    env:
      DB_NAME: ${{ vars.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ vars.HOST }}
      PORT: ${{ vars.PORT }}

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Set up MySQL
        run: |
            sudo /etc/init.d/mysql start
            mysql -e 'CREATE DATABASE ${{ env.DB_NAME }};' -u${{ env.DB_USERNAME }} -p${{ env.DB_PASSWORD }}
        timeout-minutes: 1

      - name: Check MySQL service status
        run: sudo /etc/init.d/mysql status

      - name: Check MySQL error log
        run: sudo cat /var/log/mysql/error.log

      - name: Verify Sequelize connection
        run: node -e "import('./app/database/db.js').then(({ authenticate }) => authenticate()).catch(err => console.error('Unable to connect to the database:', err));"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
           node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: LOG_DIR=./logs npm test
