name: webapp test for CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: '127.0.0.1'
      PORT: ${{ secrets.PORT }}

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          MYSQL_USER: ${{ secrets.DB_USERNAME }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-timeout=20s --health-retries=3


    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

   
      - name: Wait for MySQL to be ready
        run: |
            until mysql -h 127.0.0.1 -u${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} -e "SELECT 1"; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
            done

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
           node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Start the application server in the background
        run: node index.js

      - name: Run tests
        run: npm test

    